apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp-green
  namespace: simple-webapp-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-webapp-green
  template:
    metadata:
      labels:
        app: simple-webapp-green
    spec:
      containers:
        - image: "ghcr.io/la-cc/simple-webapp:1.0.1"
          name: simple-webapp-green
          env:
            - name: APP_COLOR
              value: "green"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
      securityContext:
        runAsUser: 1000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
